### ISSUE TITLE
Helm Tiller Silent Not Working

### ISSUE THREAD

**Issue by mstoecklmayr** [rimusz/helm-tiller#64]
Hey, we are happily using your helm tiller plugin but in the lastest version, we realized that even if the "HELM_TILLER_SILENT" variable is set to true by default, we get a tiller output which makes our CI fail because it expects input. I can reproduce it when I try to start it on my VM:
`
@management-vm:~$ helm tiller start-ci
Installed Helm version v2.14.3
Installed Tiller version v2.14.3
Helm and Tiller are the same version!
Set the following vars to use tiller:
export HELM_HOST=127.0.0.1:44134
Starting Tiller...
Tiller namespace: kube-system

@management-vm:~$ [main] 2019/09/27 13:04:35 Starting Tiller v2.14.3 (tls=false)
[main] 2019/09/27 13:04:35 GRPC listening on 127.0.0.1:44134
[main] 2019/09/27 13:04:35 Probes listening on 127.0.0.1:44135
[main] 2019/09/27 13:04:35 Storage driver is Secret
[main] 2019/09/27 13:04:35 Max history per release is 20

`
The last line expects input and therefore it fails. 
Manually setting the helm tiller silent flag via export does not help either. Am I missing a new setting or is this an issue?

Thanks and best regards

**Comment by rimusz** [comment]
which exact version are you using?
That flag wasn't changed recently

**Comment by rimusz** [comment]
by default it is `false` https://github.com/rimusz/helm-tiller/blob/master/scripts/tiller.sh#L5

**Comment by mstoecklmayr** [comment]
I'm using 0.8.7. The problem also appeared suddenly and we have never seen the "Starting Tiller.." output as well.

@management-vm:~$ helm plugin list
NAME  	VERSION	DESCRIPTION                                       
tiller	0.8.7  	Start a Tiller server locally, aka Tillerless Helm

**Comment by rimusz** [comment]
yes, you are right, it is not working

**Comment by rimusz** [comment]
fixed it in v0.9.0

**Comment by rimusz** [comment]
you should never use latest version, best practices is to version everything e.g.:
`helm plugin install https://github.com/rimusz/helm-tiller --version v0.8.4`
:-)

**Comment by mstoecklmayr** [comment]
Thank you for the quick fix :)

**Comment by rimusz** [comment]
no worries
I was using older version of the plugin so dd not notice that `tiller` output was not silent.

**Comment by Morriz** [comment]
I still get an error in v0.9.0 underneath that screws up the output:
```
/root/.helm/plugins/helm-tiller/scripts/tiller.sh: line 174:   160 Killed                  ./bin/tiller --storage=${HELM_TILLER_STORAGE} --listen=127.0.0.1:${HELM_TILLER_PORT} ${PROBE_LISTEN_FLAG} --history-max=${HELM_TILLER_HISTORY_MAX}  (wd: ~/.helm/plugins/helm-tiller)
```

**Comment by Morriz** [comment]
I still see output underneath in version 0.9.0, but only sometimes:
```
/root/.helm/plugins/helm-tiller/scripts/tiller.sh: line 174:   605 Killed                  ./bin/tiller --storage=${HELM_TILLER_STORAGE} --listen=127.0.0.1:${HELM_TILLER_PORT} ${PROBE_LISTEN_FLAG} --history-max=${HELM_TILLER_HISTORY_MAX}  (wd: ~/.helm/plugins/helm-tiller)
```

Not nice since we need the output as template...

**Comment by rimusz** [comment]
@Morriz try to use version `0.8.3` as I use it and I do not see any `tiller` related messages

**Comment by Morriz** [comment]
Hi, this is still not working for 0.83, and the answer you gave is not reflecting proper release management. Why release bugs? If you know the fix can you please fix it in the latest version and release a patch?

**Comment by rimusz** [comment]
@Morriz please try `v0.9.1` which I have released with the new fix.

**Comment by luisdavim** [comment]
Oh, I didn't see this before but my PR seems related: https://github.com/rimusz/helm-tiller/pull/66
